
services:
  python_telegram_bot:
    extends:
      file: docker-compose.base.yaml
      service: python_telegram_bot
    ports:
      - "8001:8001"
    volumes:
      - ../microservices/telegram_bot/log:/app/log
    environment:
      - APP_ENVIRONMENT=local
      - APP__BOT__TOKEN=7785965888:AAH8Vq3yZgZerCs5kT2WxYaCK21alLQma8s
      - APP__REDIS__DB=0
      - APP__REDIS__ADDRESS=redis_database:6379
      
  rust_ad_engine:
    extends:
      file: docker-compose.base.yaml
      service: rust_ad_engine
    ports:
      - "8000:8000"
    volumes:
      - ../microservices/rust_ad_engine/log:/app/log
    environment:
      - APP_ENVIRONMENT=local
      - APP__HASHING__RANDOM_SECRET=b3783a3a5245fd7b95d77961766278157832feb2e93a46a6e7a86774780f1eb3d48895dda9752905cb87ca11bba23f97b409e423fe2189a923651590062b26c1
      - APP__HTTP_SERVER__HOST=0.0.0.0
      - APP__HTTP_SERVER__PORT=8000
      - APP__DATABASE__POSTGRES__POSTGRES_CONN=postgres://postgres:44541@postgres_database:5432/testy
      - APP__CORS__ALLOWED_ORIGIN=http://python_telegram_bot:8001/

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/ping"]

  postgres_database:
    extends:
      file: docker-compose.base.yaml
      service: postgres_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=44541
      - POSTGRES_DB=testy
    volumes:
      - ../infrastructure/postgres/.pgdata:/var/lib/postgresql/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d testy" ]

  redis_database:
    extends:
      file: docker-compose.base.yaml
      service: redis_database
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=44541
    volumes:
      - ../infrastructure/redis/.redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "44541", "ping"]

    