
services:      
  rust_ad_engine:
    extends:
      file: ../deploy/docker-compose.base.yaml
      service: rust_ad_engine
    container_name: rust_ad_engine_test
    ports:
      - "9000:9000"
    environment:
      - APP_ENVIRONMENT=local
      - APP__HTTP_SERVER__HOST=0.0.0.0
      - APP__HTTP_SERVER__PORT=9000
      - APP__DATABASE__POSTGRES__POSTGRES_CONN=postgres://postgres:44541@postgres_database_test:5433/ad_engine_test
      - APP__DATABASE__REDIS__HOST=redis_database_test
      - APP__DATABASE__REDIS__PORT=6380
      - APP__DATABASE__REDIS__DB=10
      - APP__YANDEX__FOLDER_ID=b1gr5pru8n2ad9c5vac9
      - APP__YANDEX__API_KEY=y0__xCbi_7lBRjB3RMgvZWgpRITxp40VTeYFNw80yDNP1V4e_mhcA

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/ping"]

  postgres_database:
    extends:
      file: ../deploy/docker-compose.base.yaml
      service: postgres_database
    container_name: postgres_database_test
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=44541
      - POSTGRES_DB=ad_engine_test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d testy" ]

  redis_database:
    extends:
      file: ../deploy/docker-compose.base.yaml
      service: redis_database
    container_name: redis_database_test
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=44541
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "44541", "ping"]

volumes:
  postgres_data_test:
