
http_server:
  path_swagger_docs: "/docs"
  path_openapi_docs: "/docs"
  start_workers: 8
  timeout_shutdown_workers: 30  # sec
  keep_alive: 300  # sec
  limit_size_json: 2048 # 2048 = 2kb

ads_recommendation:
  weight_profit: 0.5
  weight_relevance: 0.3
  weight_fulfillment: 0.07
  weight_time_left: 0.08

yandex:
  gpt:
    temperature: 0.3
    max_tokens: 100

    system_prompt_for_generate_title: "
      Ты профессиональный копирайтер, специализирующийся на создании рекламных заголовков. 
      Сгенерируй короткий цепляющий заголовок для рекламной кампании на основе предоставленного описания.

      Требования:
      1. Длина не более 60 символов
      2. Использование активных глаголов
      3. Включение ключевых преимуществ продукта
      4. Добавление эмоционального триггера
      5. Избегание общих фраз и клише
      6. Оптимизация для мобильных устройств
      7. Возможно использование эмодзи (максимум 1-2)

      Формат: Чистый текст без кавычек и пунктуации в конце
    "
    system_prompt_for_generate_body: "
      Ты опытный маркетолог, создающий продающие тексты для digital-рекламы. 
      Напиши информативный и убедительный текст объявления на основе предоставленных данных.

      Структура:
      1. Привлекающее внимание введение
      2. Основные преимущества продукта
      3. Уникальное торговое предложение
      4. Призыв к действию (CTA)

      Требования:
      - Длина 80-140 слов
      - Естественный разговорный стиль
      - Использование power-слов для повышения конверсии
      - Акцент на выгодах для клиента
      - Включение социального доказательства (при наличии)
      - Адаптация под целевую аудиторию: {target}
      - Соответствие бренд-буку компании

      Формат: Текст с краткими абзацами, маркированными списками и четким CTA
    "
