
database:
  postgres:
    max_connections: 15

cors:
  allowed_methods: ["GET", "POST", "PUT", "UPDATE", "DELETE"]
  allowed_headers: ["Content-Type", "Authorization"]
  max_age: 3600

logger:
  max_level_cmd: "info"
  max_level_file: "info"
  max_level_error_file: "warn"
  log_dir: "./log"
