
---
test_name: Успешное удаление рекламных кампаний
stages:
  - name: Ставим время
    request:
      url: "{ad_engine_url}/time/advance"
      method: POST
      json:
        current_date: 1

  - name: Создание рекламодателей
    request:
      url: "{ad_engine_url}/advertisers/bulk"
      method: POST
      json:
        - advertiser_id: "40000000-0000-0000-0000-000000000001"
          name: "user1"
    response:
      status_code: 201

  - name: Успешное создание рекламных кампаний [1]
    request:
      url: "{ad_engine_url}/advertisers/40000000-0000-0000-0000-000000000001/campaigns"
      method: POST
      json:
        ad_text: Text 1
        ad_title: Title
        clicks_limit: 50
        impressions_limit: 100
        cost_per_clicks: 100
        cost_per_impressions: 100
        end_date: 1
        start_date: 1
        targeting: {}
    response:
      status_code: 201
      save:
        json:
          campaign1_id: campaign_id

  - name: Удаление рекламной кампании по id
    request:
      url: "{ad_engine_url}/advertisers/40000000-0000-0000-0000-000000000001/campaigns/{campaign1_id}"
      method: DELETE
    response:
      status_code: 204

  - name: Удаление рекламной кампании по id снова
    request:
      url: "{ad_engine_url}/advertisers/40000000-0000-0000-0000-000000000001/campaigns/{campaign1_id}"
      method: DELETE
    response:
      status_code: 404


---
test_name: Не успешное удаление рекламных кампаний
stages:
  - name: Получение рекламной кампании по не верному id кампании
    request:
      url: "{ad_engine_url}/advertisers/40000000-0000-0000-0000-000000000001/campaigns/campaign3_id"
      method: DELETE
    response: 
      status_code: 404

  - name: Получение рекламной кампании по не верному id рекломадателя
    request:
      url: "{ad_engine_url}/advertisers/advertiser/campaigns/campaign3_id"
      method: DELETE
    response:
      status_code: 404
